name: TalkieWatch
options:
  bundleIdPrefix: jdi.talkie
  deploymentTarget:
    watchOS: "10.0"
  developmentLanguage: en

settings:
  base:
    DEVELOPMENT_TEAM: 2U83JFPW66
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.0"

targets:
  TalkieWatch:
    type: application
    platform: watchOS
    sources:
      - App
      - Views
      - Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jdi.talkie-os.watchkitapp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        WK_COMPANION_APP_BUNDLE_IDENTIFIER: jdi.talkie-os
