/**
 * Headless Mode Routes
 *
 * POST /headless        - Send message to Codex in headless mode
 * GET  /headless/status - Check if headless mode is available
 *
 * Uses Codex CLI directly (bypasses Talkie/TalkieAgent UI automation):
 * - `codex exec --json --sandbox workspace-write --cd <workspace> "message"`
 * - Works when screen is locked (no UI/AX needed)
 */

import { spawn } from "bun";
import { accessSync, constants, existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { log } from "../../log";
import { getSession } from "../../discovery/sessions";

// ===== Types =====

export interface HeadlessRequest {
  sessionId?: string;
  message: string;
  projectDir?: string;
  stream?: boolean;
}

export interface HeadlessResponse {
  success: boolean;
  response?: string;
  messageCount?: number;
  sessionId?: string;
  error?: string;
  stderr?: string;
}

export interface HeadlessStatusResponse {
  available: boolean;
  version?: string;
  error?: string;
  executable?: string;
  workspace?: string;
  profile?: string;
  profilePath?: string;
  policy?: CodexPolicy;
}

interface CodexPolicy {
  sandbox: "read-only" | "workspace-write" | "danger-full-access";
  approvalPolicy: string;
  workspace: string;
  profile: string;
  profilePath: string;
}

interface CodexJSONEvent {
  type?: string;
  thread_id?: string;
  threadId?: string;
  delta?: string;
  text?: string;
  content?: string;
  item?: {
    type?: string;
    text?: string;
    id?: string;
  };
  [key: string]: unknown;
}

interface ParsedCodexEvent {
  sessionId?: string;
  content?: string;
  completedAgentMessage?: string;
  interrupted?: boolean;
}

// ===== Config =====

const CODEX_WORKSPACE_DIR =
  process.env.TALKIE_CODEX_WORKSPACE_DIR?.trim()
  || join(homedir(), "Documents", "Talkie", "Agents", "iOS");

const CODEX_PROFILE_NAME =
  process.env.TALKIE_CODEX_PROFILE?.trim()
  || "talkie-phone";

const CODEX_PROFILE_PATH = join(homedir(), ".codex", `${CODEX_PROFILE_NAME}.config.toml`);

const CODEX_APPROVAL_POLICY =
  process.env.TALKIE_CODEX_APPROVAL_POLICY?.trim()
  || "never";

const CODEX_MODEL = process.env.TALKIE_CODEX_MODEL?.trim();

const CODEX_PROFILE_HEADER = "# Generated by TalkieServer for requests sent from Talkie on iOS.";
const CODEX_INTERRUPTED_MESSAGE = "[Request interrupted by user]";

const VALID_CODEX_SANDBOXES = new Set(["read-only", "workspace-write", "danger-full-access"]);

function codexSandbox(): CodexPolicy["sandbox"] {
  const configured = process.env.TALKIE_CODEX_SANDBOX?.trim();
  if (configured && VALID_CODEX_SANDBOXES.has(configured)) {
    return configured as CodexPolicy["sandbox"];
  }

  return "workspace-write";
}

function codexPolicy(workspace: string): CodexPolicy {
  return {
    sandbox: codexSandbox(),
    approvalPolicy: CODEX_APPROVAL_POLICY,
    workspace,
    profile: CODEX_PROFILE_NAME,
    profilePath: CODEX_PROFILE_PATH,
  };
}

// ===== Helpers =====

function isExecutable(path: string): boolean {
  try {
    accessSync(path, constants.X_OK);
    return true;
  } catch {
    return false;
  }
}

function resolveCodexExecutable(): string {
  const configured = process.env.TALKIE_CODEX_EXECUTABLE?.trim();
  if (configured) {
    return configured;
  }

  const pathCandidates = (process.env.PATH ?? "")
    .split(":")
    .filter(Boolean)
    .map((entry) => join(entry, "codex"));

  const candidates = [
    ...pathCandidates,
    join(homedir(), ".local", "bin", "codex"),
    "/Applications/Codex.app/Contents/Resources/codex",
    "/opt/homebrew/bin/codex",
    "/usr/local/bin/codex",
  ];

  return candidates.find(isExecutable) ?? "codex";
}

async function resolveWorkingDirectory(projectDir?: string, sessionId?: string): Promise<string> {
  if (projectDir?.trim()) {
    return projectDir.trim();
  }

  // Backward-compatible only: older iOS sessions may still hold a Claude session id.
  // New Codex thread ids will not resolve through Claude's transcript cache.
  if (sessionId) {
    const session = await getSession(sessionId);
    if (session?.projectPath) {
      return session.projectPath;
    }
  }

  return CODEX_WORKSPACE_DIR;
}

async function ensureCodexWorkspace(workingDir: string): Promise<void> {
  await mkdir(workingDir, { recursive: true, mode: 0o700 });

  if (workingDir !== CODEX_WORKSPACE_DIR) {
    return;
  }

  const agentsPath = join(workingDir, "AGENTS.md");
  if (existsSync(agentsPath)) {
    return;
  }

  await writeFile(
    agentsPath,
    `# Talkie iOS Ask Agent

You are Codex answering requests from Talkie on iOS.

Policy:
- Treat this directory as your writable workspace.
- Create and edit files here unless the user explicitly names another path.
- Do not modify Talkie application settings, credentials, or databases unless the user explicitly asks for that.
- Prefer concise answers for memo analysis. When you create a file, mention the path.
`,
    { mode: 0o600 }
  );
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function codexPhoneProfileContents(policy: CodexPolicy): string {
  const modelLine = CODEX_MODEL
    ? `model = ${tomlString(CODEX_MODEL)}\n`
    : "";

  return `${CODEX_PROFILE_HEADER}
# Edit this profile to tune phone-originated Codex behavior.

${modelLine}approval_policy = ${tomlString(policy.approvalPolicy)}
sandbox_mode = ${tomlString(policy.sandbox)}

[projects.${tomlString(policy.workspace)}]
trust_level = "trusted"
`;
}

async function ensureCodexProfile(policy: CodexPolicy): Promise<void> {
  await mkdir(join(homedir(), ".codex"), { recursive: true, mode: 0o700 });

  if (existsSync(policy.profilePath)) {
    const existing = await readFile(policy.profilePath, "utf8");
    if (!existing.startsWith(CODEX_PROFILE_HEADER)) {
      return;
    }
  }

  await writeFile(policy.profilePath, codexPhoneProfileContents(policy), { mode: 0o600 });
}

function baseCodexArgs(policy: CodexPolicy): string[] {
  const args = [
    "exec",
    "--profile",
    policy.profile,
    "--json",
  ];

  if (CODEX_MODEL) {
    args.push("-m", CODEX_MODEL);
  }

  return args;
}

function codexArgsForRequest(
  message: string,
  workingDir: string,
  policy: CodexPolicy,
  sessionId?: string
): string[] {
  if (sessionId) {
    const resumeArgs = [
      "exec",
      "--profile",
      policy.profile,
      "resume",
      "--json",
    ];

    if (CODEX_MODEL) {
      resumeArgs.push("-m", CODEX_MODEL);
    }

    resumeArgs.push(
      "--skip-git-repo-check",
      sessionId,
      "--",
      message,
    );

    return resumeArgs;
  }

  return [
    ...baseCodexArgs(policy),
    "--cd",
    workingDir,
    "--skip-git-repo-check",
    "--",
    message,
  ];
}

function parseCodexJSONLine(line: string): ParsedCodexEvent | null {
  let event: CodexJSONEvent;
  try {
    event = JSON.parse(line) as CodexJSONEvent;
  } catch {
    return null;
  }

  if (event.type === "thread.started") {
    const sessionId = event.thread_id ?? event.threadId;
    return typeof sessionId === "string" ? { sessionId } : {};
  }

  if (event.type === "item.completed" && event.item?.type === "agent_message") {
    if (typeof event.item.text !== "string") {
      return {};
    }
    if (event.item.text.trim() === CODEX_INTERRUPTED_MESSAGE) {
      return { interrupted: true };
    }

    return { completedAgentMessage: event.item.text };
  }

  const directContent = event.delta ?? event.text ?? event.content;
  if (typeof directContent === "string" && directContent.length > 0) {
    if (directContent.trim() === CODEX_INTERRUPTED_MESSAGE) {
      return { interrupted: true };
    }

    return { content: directContent };
  }

  return {};
}

function parseCodexOutput(stdout: string): { response: string; sessionId?: string; interrupted: boolean } {
  let response = "";
  let completedAgentMessage = "";
  let sawIncrementalContent = false;
  let sessionId: string | undefined;
  let interrupted = false;

  for (const line of stdout.split("\n")) {
    const parsed = parseCodexJSONLine(line.trim());
    if (!parsed) {
      continue;
    }

    if (parsed.sessionId) {
      sessionId = parsed.sessionId;
    }

    if (parsed.interrupted) {
      interrupted = true;
      continue;
    }

    if (parsed.content) {
      sawIncrementalContent = true;
      response += parsed.content;
    }

    if (parsed.completedAgentMessage) {
      completedAgentMessage = parsed.completedAgentMessage;
    }
  }

  if (!response && completedAgentMessage) {
    response = completedAgentMessage;
  } else if (!sawIncrementalContent && completedAgentMessage) {
    response = completedAgentMessage;
  }

  return { response, sessionId, interrupted };
}

async function collectStream(stream: ReadableStream<Uint8Array> | null): Promise<string> {
  if (!stream) {
    return "";
  }
  return new Response(stream).text();
}

// ===== Handlers =====

/**
 * POST /headless
 * Send message to Codex in headless mode
 */
export async function headlessRoute(body: HeadlessRequest): Promise<Response> {
  const { sessionId, message, projectDir, stream = false } = body;

  const workingDir = await resolveWorkingDirectory(projectDir, sessionId);
  await ensureCodexWorkspace(workingDir);
  const policy = codexPolicy(workingDir);
  await ensureCodexProfile(policy);
  const executable = resolveCodexExecutable();

  log.info(
    `Headless Codex: sessionId=${sessionId || "(new)"}, workspace=${workingDir}, sandbox=${policy.sandbox}, message=${message.slice(0, 100)}...`
  );

  const args = codexArgsForRequest(message, workingDir, policy, sessionId);
  const proc = spawn({
    cmd: [executable, ...args],
    cwd: workingDir || process.cwd(),
    stdin: "ignore",
    stdout: "pipe",
    stderr: "pipe",
    env: {
      ...process.env,
      TERM: "dumb",
      NO_COLOR: "1",
    },
  });

  if (stream) {
    // Return Server-Sent Events stream
    return new Response(
      new ReadableStream({
        async start(controller) {
          const encoder = new TextEncoder();
          let capturedSessionId: string | undefined;
          let sawIncrementalContent = false;
          let completedAgentMessage = "";
          let interrupted = false;
          const stderrPromise = collectStream(proc.stderr);

          function processLine(line: string) {
            const parsed = parseCodexJSONLine(line.trim());
            if (!parsed) {
              return;
            }

            if (parsed.sessionId) {
              capturedSessionId = parsed.sessionId;
            }

            if (parsed.interrupted) {
              interrupted = true;
              return;
            }

            if (parsed.content) {
              sawIncrementalContent = true;
              controller.enqueue(encoder.encode(`data: ${JSON.stringify({ type: "assistant", content: parsed.content })}\n\n`));
            }

            if (parsed.completedAgentMessage) {
              completedAgentMessage = parsed.completedAgentMessage;
            }
          }

          try {
            const reader = proc.stdout.getReader();
            let buffer = "";

            while (true) {
              const { done, value } = await reader.read();
              if (done) break;

              const text = new TextDecoder().decode(value);
              buffer += text;

              const lines = buffer.split("\n");
              buffer = lines.pop() || "";

              for (const line of lines) {
                processLine(line);
              }
            }

            if (buffer.trim()) {
              processLine(buffer);
            }

            if (interrupted) {
              controller.enqueue(encoder.encode(`data: ${JSON.stringify({ type: "error", error: "Codex request was interrupted before it completed." })}\n\n`));
            } else if (!sawIncrementalContent && completedAgentMessage) {
              controller.enqueue(encoder.encode(`data: ${JSON.stringify({ type: "assistant", content: completedAgentMessage })}\n\n`));
            }

            const [exitCode, stderr] = await Promise.all([proc.exited, stderrPromise]);
            if (exitCode !== 0) {
              log.error(`Headless Codex error (exit ${exitCode}): ${stderr}`);
              controller.enqueue(encoder.encode(`data: ${JSON.stringify({ type: "error", error: `Codex exited with code ${exitCode}` })}\n\n`));
            } else if (stderr.trim()) {
              log.debug(`Headless Codex stderr: ${stderr.trim().slice(0, 500)}`);
            }

            // Send session_id as a metadata event before DONE
            if (capturedSessionId) {
              controller.enqueue(encoder.encode(`data: ${JSON.stringify({ type: "session", session_id: capturedSessionId })}\n\n`));
            }

            controller.enqueue(encoder.encode("data: [DONE]\n\n"));
            controller.close();
          } catch (error) {
            log.error(`Headless Codex stream error: ${error}`);
            controller.enqueue(encoder.encode(`data: ${JSON.stringify({ type: "error", error: String(error) })}\n\n`));
            controller.close();
          }
        },
      }),
      {
        headers: {
          "Content-Type": "text/event-stream",
          "Cache-Control": "no-cache",
          "Connection": "keep-alive",
        },
      }
    );
  }

  // Non-streaming: collect full response
  try {
    const stdout = await new Response(proc.stdout).text();
    const stderr = await new Response(proc.stderr).text();
    const exitCode = await proc.exited;

    if (exitCode !== 0) {
      log.error(`Headless Codex error (exit ${exitCode}): ${stderr}`);
      return Response.json({
        success: false,
        error: `Codex exited with code ${exitCode}`,
        stderr: stderr.slice(0, 500),
      } satisfies HeadlessResponse, { status: 500 });
    }

    const result = parseCodexOutput(stdout);

    if (result.interrupted) {
      log.warning("Headless Codex request was interrupted before completion");
      return Response.json({
        success: false,
        error: "Codex request was interrupted before it completed.",
        sessionId: result.sessionId ?? sessionId,
      } satisfies HeadlessResponse, { status: 500 });
    }

    log.info(`Headless Codex complete: ${result.response.length} chars response`);

    return Response.json({
      success: true,
      response: result.response,
      messageCount: result.response.length === 0 ? 0 : 1,
      sessionId: result.sessionId ?? sessionId,
    } satisfies HeadlessResponse);
  } catch (error) {
    log.error(`Headless Codex error: ${error}`);
    return Response.json({
      success: false,
      error: String(error),
    } satisfies HeadlessResponse, { status: 500 });
  }
}

/**
 * GET /headless/status
 * Check if headless mode is available
 */
export async function headlessStatusRoute(): Promise<HeadlessStatusResponse> {
  const executable = resolveCodexExecutable();
  const workspace = CODEX_WORKSPACE_DIR;
  const policy = codexPolicy(workspace);
  await ensureCodexWorkspace(workspace);
  await ensureCodexProfile(policy);

  try {
    const proc = spawn({
      cmd: [executable, "--version"],
      stdout: "pipe",
      stderr: "pipe",
    });

    const stdout = await new Response(proc.stdout).text();
    const stderr = await new Response(proc.stderr).text();
    const exitCode = await proc.exited;

    if (exitCode === 0) {
      return {
        available: true,
        version: stdout.trim(),
        executable,
        workspace,
        profile: policy.profile,
        profilePath: policy.profilePath,
        policy,
      };
    }

    return {
      available: false,
      error: stderr.trim() || "Codex CLI not responding",
      executable,
      workspace,
      profile: policy.profile,
      profilePath: policy.profilePath,
      policy,
    };
  } catch (error) {
    return {
      available: false,
      error: String(error),
      executable,
      workspace,
      profile: policy.profile,
      profilePath: policy.profilePath,
      policy,
    };
  }
}
