name: Talkie
options:
  bundleIdPrefix: jdi
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en

settings:
  base:
    DEVELOPMENT_TEAM: 2U83JFPW66
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.0"

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    version: 0.15.0
  FluidAudio:
    url: https://github.com/FluidInference/FluidAudio.git
    version: 0.7.11
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    version: 7.8.0
  TalkieServices:
    path: ../TalkieServices

targets:
  Talkie:
    type: application
    platform: macOS
    sources:
      - path: Talkie
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: WhisperKit
      - package: FluidAudio
      - package: GRDB
      - package: TalkieServices
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jdi.talkie-os-mac
        MARKETING_VERSION: "1.1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_CFBundleDisplayName: "Talkie"
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        CODE_SIGN_ENTITLEMENTS: Talkie/Talkie.entitlements
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_NSAppleEventsUsageDescription: "Talkie needs to communicate with Notes, Reminders, and Calendar to save your voice memo content."
