name: Talkie
options:
  bundleIdPrefix: jdi
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en
  createIntermediateGroups: true

configs:
  Debug: debug
  Staging: release
  Release: release

settings:
  base:
    DEVELOPMENT_TEAM: 2U83JFPW66
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.0"
    ENABLE_HARDENED_RUNTIME: YES
    ARCHS: arm64  # Apple Silicon only
  configs:
    Debug:
      PRODUCT_BUNDLE_IDENTIFIER: jdi.talkie.core.dev
      URL_SCHEME: talkie-dev
    Staging:
      PRODUCT_BUNDLE_IDENTIFIER: jdi.talkie.core.staging
      URL_SCHEME: talkie-staging
      CODE_SIGN_ENTITLEMENTS: Talkie-Staging.entitlements
      ENABLE_HARDENED_RUNTIME: NO
      # Keep debug symbols for debugging - staging is a dev build
    Release:
      PRODUCT_BUNDLE_IDENTIFIER: jdi.talkie.core
      URL_SCHEME: talkie
      # Optimize for size
      DEAD_CODE_STRIPPING: YES
      COPY_PHASE_STRIP: YES
      SWIFT_OPTIMIZATION_LEVEL: -Osize

packages:
  TalkieKit:
    path: ../TalkieKit
  DebugKit:
    path: ../../Packages/DebugKit
  FluidAudio:
    url: https://github.com/FluidInference/FluidAudio.git
    version: 0.7.11
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    version: 7.8.0
  WFKit:
    path: ../../Packages/WFKit
  mlx-swift:
    url: https://github.com/ml-explore/mlx-swift.git
    version: 0.29.1
  mlx-swift-lm:
    url: https://github.com/ml-explore/mlx-swift-lm.git
    version: 2.29.2

targets:
  Talkie:
    type: application
    platform: macOS
    sources:
      - path: App
        type: group
      - path: Components
        type: group
      - path: Data
        type: group
        excludes:
          - "*.md"
      - path: Database
        type: group
      - path: Debug
        type: group
        excludes:
          - "*.md"
      - path: Interstitial
        type: group
      - path: Models
        type: group
      - path: Resources
        type: folder
      - path: Services
        type: group
      - path: Stores
        type: group
      - path: Views
        type: group
      - path: Workflow
        type: group
      - Assets.xcassets
    info:
      path: Talkie-Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: Talkie URL
            CFBundleURLSchemes:
              - $(URL_SCHEME)
    dependencies:
      - package: TalkieKit
      - package: DebugKit
      - package: FluidAudio
      - package: GRDB
      - package: WFKit
      - package: mlx-swift
        product: MLX
      - package: mlx-swift-lm
        product: MLXLLM
      - package: mlx-swift-lm
        product: MLXLMCommon
    settings:
      base:
        MARKETING_VERSION: "1.7.12"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_CFBundleDisplayName: "Talkie"
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        CODE_SIGN_ENTITLEMENTS: Talkie.entitlements
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_NSAppleEventsUsageDescription: "Talkie needs to communicate with Notes, Reminders, and Calendar to save your voice memo content."
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Talkie needs access to your microphone to record voice memos for transcription."

schemes:
  Talkie:
    build:
      targets:
        Talkie: all
    run:
      config: Debug
    archive:
      config: Release
  Talkie-Staging:
    build:
      targets:
        Talkie: all
    run:
      config: Staging
    archive:
      config: Staging
