name: Talkie
options:
  bundleIdPrefix: jdi
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en

settings:
  base:
    DEVELOPMENT_TEAM: 2U83JFPW66
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.0"
    ENABLE_HARDENED_RUNTIME: YES

packages:
  TalkieKit:
    path: ../TalkieKit
  DebugKit:
    path: ../../../DebugKit
  FluidAudio:
    url: https://github.com/FluidInference/FluidAudio.git
    version: 0.7.11
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    version: 7.8.0
  WFKit:
    path: ../../WFKit
  mlx-swift:
    url: https://github.com/ml-explore/mlx-swift.git
    version: 0.29.1
  mlx-swift-lm:
    url: https://github.com/ml-explore/mlx-swift-lm.git
    version: 2.29.2

targets:
  Talkie:
    type: application
    platform: macOS
    sources:
      - App
      - Models
      - Views
      - Services
      - Workflow
      - Resources
      - Assets.xcassets
      - Interstitial
    info:
      path: Talkie-Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: Talkie URL
            CFBundleURLSchemes:
              - talkie
    dependencies:
      - package: TalkieKit
      - package: DebugKit
      - package: FluidAudio
      - package: GRDB
      - package: WFKit
      - package: mlx-swift
        product: MLX
      - package: mlx-swift-lm
        product: MLXLLM
      - package: mlx-swift-lm
        product: MLXLMCommon
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jdi.talkie.core
        MARKETING_VERSION: "1.6.1"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_CFBundleDisplayName: "Talkie"
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        CODE_SIGN_ENTITLEMENTS: Talkie.entitlements
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_NSAppleEventsUsageDescription: "Talkie needs to communicate with Notes, Reminders, and Calendar to save your voice memo content."
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Talkie needs access to your microphone to record voice memos for transcription."

schemes:
  Talkie:
    build:
      targets:
        Talkie: all
    run:
      config: Debug
    archive:
      config: Release
