name: TalkieEngine
options:
  bundleIdPrefix: jdi
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

configs:
  Debug: debug
  Staging: release
  Release: release

schemes:
  TalkieEngine:
    build:
      targets:
        TalkieEngine: all
    run:
      config: Debug
    archive:
      config: Release
  TalkieEngine-Staging:
    build:
      targets:
        TalkieEngine: all
    run:
      config: Staging
    archive:
      config: Staging

settings:
  base:
    ARCHS: arm64  # Apple Silicon only - MLX requires it anyway
    DEVELOPMENT_TEAM: 2U83JFPW66
    CODE_SIGN_STYLE: Automatic
  configs:
    Debug:
      PRODUCT_BUNDLE_IDENTIFIER: jdi.talkie.engine.dev
    Staging:
      PRODUCT_BUNDLE_IDENTIFIER: jdi.talkie.engine.staging
    Release:
      PRODUCT_BUNDLE_IDENTIFIER: jdi.talkie.engine

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.9.0"
  FluidAudio:
    url: https://github.com/FluidInference/FluidAudio.git
    version: 0.7.11
  TalkieKit:
    path: ../TalkieKit

targets:
  TalkieEngine:
    type: application
    platform: macOS
    sources:
      - path: TalkieEngine
    settings:
      base:
        INFOPLIST_FILE: TalkieEngine/Info.plist
        CODE_SIGN_ENTITLEMENTS: TalkieEngine/TalkieEngine.entitlements
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "5.9"
        PRODUCT_NAME: TalkieEngine
        ENABLE_HARDENED_RUNTIME: YES
    dependencies:
      - package: WhisperKit
      - package: FluidAudio
      - package: TalkieKit
