#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR/services/talkie-admin"

keys=(
  TALKIE_ADMIN_API_KEY
  TALKIE_ADMIN_BLOB_READ_WRITE_TOKEN
  TALKIE_ADMIN_LOCAL_VERCEL_OIDC_TOKEN
)

while IFS= read -r key; do
  case "$key" in
    TALKIE_ADMIN_GITHUB_ADMIN_TOKEN|TALKIE_ADMIN_GITHUB_REPO_OWNER|TALKIE_ADMIN_GITHUB_REPO_NAME|TALKIE_ADMIN_SUPABASE_URL|TALKIE_ADMIN_SUPABASE_ANON_KEY)
      keys+=("$key")
      ;;
  esac
done < <(secret list)

exec secret run "${keys[@]}" -- sh -c '
  export API_KEY="$TALKIE_ADMIN_API_KEY"
  export BLOB_READ_WRITE_TOKEN="$TALKIE_ADMIN_BLOB_READ_WRITE_TOKEN"
  export VERCEL_OIDC_TOKEN="$TALKIE_ADMIN_LOCAL_VERCEL_OIDC_TOKEN"

  [ -n "${TALKIE_ADMIN_GITHUB_ADMIN_TOKEN:-}" ] && export GITHUB_ADMIN_TOKEN="$TALKIE_ADMIN_GITHUB_ADMIN_TOKEN"
  [ -n "${TALKIE_ADMIN_GITHUB_REPO_OWNER:-}" ] && export GITHUB_REPO_OWNER="$TALKIE_ADMIN_GITHUB_REPO_OWNER"
  [ -n "${TALKIE_ADMIN_GITHUB_REPO_NAME:-}" ] && export GITHUB_REPO_NAME="$TALKIE_ADMIN_GITHUB_REPO_NAME"
  [ -n "${TALKIE_ADMIN_SUPABASE_URL:-}" ] && export NEXT_PUBLIC_SUPABASE_URL="$TALKIE_ADMIN_SUPABASE_URL"
  [ -n "${TALKIE_ADMIN_SUPABASE_ANON_KEY:-}" ] && export NEXT_PUBLIC_SUPABASE_ANON_KEY="$TALKIE_ADMIN_SUPABASE_ANON_KEY"

  exec npm run dev
'
