#!/bin/bash
#
# Generate BuildInfo.generated.swift for iOS app
# Add this as a Run Script build phase in Xcode (before Compile Sources)
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="$REPO_ROOT/iOS/Talkie iOS/BuildInfo.generated.swift"

# Get git info
GIT_BRANCH=$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_DATE=$(date "+%Y-%m-%d %H:%M")

cat > "$OUTPUT_FILE" << EOF
//
//  BuildInfo.generated.swift
//  Talkie iOS
//
//  Auto-generated by scripts/generate-ios-build-info.sh
//  Do not edit manually - this file is regenerated on each build
//

import Foundation

enum BuildInfo {
    static let gitBranch = "$GIT_BRANCH"
    static let gitCommit = "$GIT_COMMIT"
    static let buildDate = "$BUILD_DATE"
}
EOF

echo "Generated BuildInfo: branch=$GIT_BRANCH commit=$GIT_COMMIT"
