//
//  BuildInfo.generated.swift
//  Talkie iOS
//
//  Auto-generated by scripts/generate-ios-build-info.sh
//  Do not edit manually - this file is regenerated on each build
//

import Foundation

enum BuildInfo {
    static let gitBranch = "feature/connection-center"
    static let gitCommit = "1084f07"
    static let buildDate = "2026-01-08 17:26"
}
